networks:
  capstone_net:
    driver: bridge

volumes:
  db_data:

services:

  kong:
    image: kong:3.6
    container_name: capstone-kong
    restart: unless-stopped
    ports:
      - "443:443"    
      - "8080:8000"  
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: "/kong/kong.yml"
      KONG_PROXY_LISTEN: "0.0.0.0:443 ssl, 0.0.0.0:8000"
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
    volumes:
      - ./kong/kong.yml:/kong/kong.yml:ro
    networks: [capstone_net]
    depends_on:
      - oauth2-proxy
      - backend

  redis:
    image: redis:7-alpine
    container_name: capstone-redis
    restart: unless-stopped
    networks: [capstone_net]

  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.6.0
    container_name: capstone-oauth2-proxy
    restart: unless-stopped
    env_file:
      - ./capstone-oauth2-proxy/.env
    networks: [capstone_net]

  database:
    image: postgres:18
    container_name: capstone-database
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres/25
      POSTGRES_DB: kmall_db
    ports:
      - "5555:5432"
    volumes:
      - db_data:/var/lib/postgresql
      - ./capstone-database/init:/docker-entrypoint-initdb.d
    networks: [capstone_net]

  backend:
    build: ./capstone-backend
    container_name: capstone-backend
    restart: unless-stopped
    env_file:
      - ./capstone-backend/.env
    expose:
      - "8080"
    networks:
      - capstone_net
    depends_on:
      - database

  frontend:
    build: ./capstone-frontend
    container_name: capstone-frontend
    restart: unless-stopped
    volumes:
      - ./capstone-frontend:/app
      - /app/node_modules
    networks:
      - capstone_net
    depends_on:
      - backend
